In [ ]:
import pickle

In [ ]:
# Load the saved model using pickle
with open("/content/transaction_pickle", 'rb') as file:
    model = pickle.load(file)

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_excel("/content/data_version_excel_v2.xlsx")
data.head()

,Unnamed: 0,Date,Id_compte,amount_transaction,category_transaction,Description,Type_transaction
0,0,2022-01-01 16:01:00,SEW0C_LI.1,3.39,Food & Drink - Coffee and tea,Latte purchase,Debit
1,1,2022-01-01 19:46:00,SEW0C_LI.1,3.39,Bank Transfers - ATM withdrawals,ATM withdrawal - $,Debit
2,2,2022-01-01 06:47:00,SEW0C_LI.1,3.39,Transportation - Public Transport,Bus fare payment,Debit
3,3,2022-01-01 19:22:00,SEW0C_LI.1,1.70,Transportation - Public Transport,Train ticket purchase,Debit
4,4,2022-01-01 05:49:00,SEW0C_LI.1,3.39,Transportation - Public Transport,Subway ride cost,Debit


In [ ]:
# Set the max_rows option to display all categories
pd.set_option('display.max_rows', None)

# Calculate the frequency counts
categories = data['category_transaction'].unique()



# Print the frequency counts
print(categories)

['Food & Drink - Coffee and tea' 'Bank Transfers - ATM withdrawals'
 'Transportation - Public Transport' 'Bank Transfers - ATM fees'
 'Food & Drink - Vending machines' 'Transportation - Parking'
 'Bank Transfers - Other bank fees' 'Supermarkets - Groceries'
 'Medical - Pharmacies and supplements' 'Food & Drink - Groceries'
 'General Services - Home Repair + Maintenance'
 'General Merchandise - Houseware' 'Transportation-Taxis and rideshares'
 'Transportation - Gas' 'Transportation - Tolls'
 'Food & Drink - Restaurants' 'General Merchandise - Clothing'
 'Food & Drink - Fast food' 'Bank Transfers - Overdraft fees'
 'Bank Transfers - Foreign transaction fees' 'General Merchandise - Books'
 'Entertainment - Amusement Parks' 'Medical - Veterinary services'
 'Food & Drink - Food delivery' 'Food & Drink - Alcohol & Bars'
 'General Merchandise - Pet supplies' 'Entertainment - Video games'
 'Entertainment - TV and movies' 'Entertainment - Other'
 'General Merchandise - Sporting goods'
 'General

In [ ]:
data['category_transaction'].value_counts()

Bank Transfers - ATM fees                                          4376
Transportation - Public Transport                                  3611
Transportation - Parking                                           2778
Bank Transfers - ATM withdrawals                                   2556
Food & Drink - Coffee and tea                                      2540
Food & Drink - Vending machines                                    1471
Bank Transfers - Other bank fees                                   1079
Medical - Pharmacies and supplements                                694
Transportation-Taxis and rideshares                                 507
Food & Drink - Groceries                                            384
Transportation - Tolls                                              375
Transportation - Gas                                                356
General Services - Home Repair + Maintenance                        267
Bank Transfers - Overdraft fees                                 

In [ ]:
IDs = data['Id_compte'].unique()



# Print the frequency counts
print(IDs)

['SEW0C_LI.1' 'SEW0C_HI.1' 'SEWC_CL.1' 'US.1' 'IPA.1' 'SEWC_P.1'
 'SEWC_PA.1' 'TA.1' 'HP.1' 'CPA.1' 'CPA_MP.1' 'SEWC_P_PL.1']


In [ ]:
datagpt=pd.read_excel("/content/mockdata.xlsx")
datagpt.head()

,Account ID,Transaction Amount,Transaction Description,Transaction Category
0,SEW0C_LI.1,20.50,Starbucks - Grande Cappuccino,Food & Drink - Coffee and tea
1,SEW0C_LI.1,15.75,Freshmart - Organic Vegetables,Supermarkets - Groceries
2,SEW0C_LI.1,50.00,Trendy Threads - Summer Dress,General Merchandise - Clothing
3,SEW0C_LI.1,8.99,City Cab - Ride to Airport,Transportation - Taxis and rideshares
4,SEW0C_LI.1,12.00,"Bookworm's Paradise - ""The Alchemist""",General Merchandise - Books


In [ ]:
double=datagpt[datagpt.duplicated()]
double

,Account ID,Transaction Amount,Transaction Description,Transaction Category
175,HP.1,10.00,GlobalBank - Other Bank Fee,Bank Transfers - Other bank fees
217,SEW0C_HI.1,6.25,Morning Brew - Medium Iced Coffee,Food & Drink - Coffee and tea
218,SEW0C_HI.1,12.50,Pizza Palace - Family Pizza Combo,Food & Drink - Restaurants
219,SEW0C_HI.1,38.00,Gas Stop - Fuel,Transportation - Gas
220,SEW0C_HI.1,16.99,Home Essentials - Cleaning Supplies,General Merchandise - Houseware
...,...,...,...,...
2938,SEW0C_LI.1,215.00,Professional House Cleaning Service,General Services - Other non-entertainment
2939,SEW0C_HI.1,185.00,Garden Landscaping and Maintenance,General Services - Other non-entertainment
2940,SEWC_CL.1,145.00,Personal Fitness Training Sessions,General Services - Other non-entertainment
2941,US.1,310.00,Legal Consultation and Advisory Services,General Services - Other non-entertainment


In [ ]:
datagpt.drop_duplicates(inplace=True)
double=datagpt[datagpt.duplicated()]
double

,Account ID,Transaction Amount,Transaction Description,Transaction Category


In [ ]:
datagpt.shape

(2136, 4)

In [ ]:
datagpt['Transaction Category'].value_counts()

Bank Transfers - Overdraft fees              81
General Services - Education                 69
Travel - Rental cars                         62
Entertainment - TV and movies                62
Credit card payment                          62
                                             ..
Transportation - Public Transport             6
Bank Transfers - Other bank fees              5
Travel - Lodging                              3
General Merchandise - Online Marketplaces     3
Medical - Veterin ary services                2
Name: Transaction Category, Length: 68, dtype: int64

In [ ]:
# Perform one-hot encoding for the "account_id" feature
encoded_data = pd.get_dummies(datagpt, columns=['Account ID'], prefix='account')
# Print the encoded data
print(encoded_data.head())

   Transaction Amount                Transaction Description  \
0               20.50          Starbucks - Grande Cappuccino   
1               15.75         Freshmart - Organic Vegetables   
2               50.00          Trendy Threads - Summer Dress   
3                8.99             City Cab - Ride to Airport   
4               12.00  Bookworm's Paradise - "The Alchemist"   

                    Transaction Category  account_CPA.1  account_CPA_MP.1  \
0          Food & Drink - Coffee and tea              0                 0   
1               Supermarkets - Groceries              0                 0   
2         General Merchandise - Clothing              0                 0   
3  Transportation - Taxis and rideshares              0                 0   
4            General Merchandise - Books              0                 0   

   account_HP.1  account_IPA.1  account_SEW0C_HI.1  account_SEW0C_LI.1  \
0             0              0                   0                   1   
1   

In [ ]:
one_hot_ID=encoded_data.drop(['Transaction Amount','Transaction Category','Transaction Description'], axis =1)

In [ ]:
one_hot_array=one_hot_ID.values
one_hot_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
# Extract the 'transaction amount' column
transaction_amount = datagpt['Transaction Amount']

In [ ]:
# Create an instance of the MinMaxScaler
scaler = MinMaxScaler()
# Fit and transform the transaction amount data
scaled_transaction_amount = scaler.fit_transform(transaction_amount.values.reshape(-1, 1))
# Update the 'transaction amount' column with the scaled values
datagpt['transaction_amount'] = scaled_transaction_amount
# Print the scaled 'transaction amount' column
print(datagpt['transaction_amount'])

0       0.002580
1       0.001837
2       0.007192
3       0.000780
4       0.001251
5       0.003361
6       0.030644
7       0.006410
8       0.005002
9       0.000195
10      0.000938
11      0.005629
12      0.002344
13      0.015009
14      0.000391
15      0.011882
16      0.001720
17      0.004065
18      0.000624
19      0.007192
20      0.002502
21      0.000235
22      0.001720
23      0.011882
24      0.000938
25      0.003283
26      0.002502
27      0.007192
28      0.022827
29      0.001406
30      0.000937
31      0.000625
32      0.030644
33      0.001720
34      0.003283
35      0.008755
36      0.030644
37      0.000156
38      0.000938
39      0.001875
40      0.015009
41      0.000704
42      0.000156
43      0.001720
44      0.046279
45      0.000625
46      0.002502
47      0.001251
48      0.022827
49      0.003283
50      0.000938
51      0.005629
52      0.001406
53      0.006410
54      0.022827
55      0.002502
56      0.000625
57      0.030644
58      0.0017

In [ ]:
scaled_transaction_amount

array([[0.00257974],
       [0.00183709],
       [0.00719199],
       ...,
       [0.00953721],
       [0.01969981],
       [0.02908068]])

In [ ]:
datagpt.describe()

,Transaction Amount,transaction_amount
count,2136.000000,2136.000000
mean,395.883680,0.061270
std,1056.315803,0.165153
min,4.000000,0.000000
25%,22.000000,0.002814
50%,70.800000,0.010444
75%,290.000000,0.044715
max,6400.000000,1.000000


In [ ]:
from sklearn.preprocessing import LabelEncoder
# Create an instance of LabelEncoder
label_encoder = LabelEncoder()
categories=datagpt['Transaction Category'].tolist()
# Fit the encoder to the categories and transform the data
encoded_labels = label_encoder.fit_transform(categories)
# Print the encoded cat
print(encoded_labels)


[13 58 20 ... 34 34 34]


In [ ]:
label_encoder.classes_

array(['Bank Transfers - ATM fees', 'Bank Transfers - ATM withdrawals',
       'Bank Transfers - Banking rewards',
       'Bank Transfers - Foreign transaction fees',
       'Bank Transfers - Other bank fees',
       'Bank Transfers - Overdraft fees', 'Credit card payment',
       'Entertainment - Amusement Parks',
       'Entertainment - Casinos and gambling', 'Entertainment - Other',
       'Entertainment - TV and movies', 'Entertainment - Video games',
       'Food & Drink - Alcohol & Bars', 'Food & Drink - Coffee and tea',
       'Food & Drink - Fast food', 'Food & Drink - Food delivery',
       'Food & Drink - Groceries', 'Food & Drink - Restaurants',
       'Food & Drink - Vending machines', 'General Merchandise - Books',
       'General Merchandise - Clothing',
       'General Merchandise - Electronics',
       'General Merchandise - Houseware',
       'General Merchandise - Online Marketplaces',
       'General Merchandise - Pet supplies',
       'General Merchandise - Product 

In [ ]:
pip install sentence_transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 1.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 13.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 25.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 23.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 36.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 40.6 MB/s eta 0:00:00
  Created wheel for sentence_transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125926 sha256=518c3afc5b4c73ea2747374403ca5db71f4942acc37b86eb751bd2edd88a7eb9
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence_transformers


In [ ]:
from sentence_transformers import SentenceTransformer
#sentences = ["This is an example sentence", "Each sentence is converted"]
modeld = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')


In [ ]:
import pickle
with open('embedding_pickle','wb') as f:
 pickle.dump(modeld,f)

In [ ]:
description=datagpt['Transaction Description'].tolist()
embeddings = modeld.encode(description)


In [ ]:
embeddings


array([[ 0.01363903,  0.02460667, -0.01300609, ...,  0.00662549,
        -0.00827213, -0.03044553],
       [ 0.01149002,  0.04829252, -0.00755107, ..., -0.02224092,
        -0.0387673 , -0.02491017],
       [-0.04387978, -0.05286455, -0.00526158, ...,  0.03130069,
        -0.05004961,  0.00435957],
       ...,
       [ 0.03993556,  0.01457984, -0.0148067 , ..., -0.02186158,
         0.03909984, -0.02857721],
       [ 0.04097003, -0.07378092, -0.02182727, ..., -0.01233724,
        -0.020834  ,  0.01221257],
       [ 0.04415144,  0.04374549,  0.0096705 , ..., -0.02912224,
        -0.03370368,  0.00446712]], dtype=float32)

In [ ]:
import numpy as np
features=np.concatenate((one_hot_array,scaled_transaction_amount,embeddings),axis = 1)
features

array([[ 0.        ,  0.        ,  0.        , ...,  0.00662549,
        -0.00827213, -0.03044553],
       [ 0.        ,  0.        ,  0.        , ..., -0.02224092,
        -0.0387673 , -0.02491017],
       [ 0.        ,  0.        ,  0.        , ...,  0.03130069,
        -0.05004961,  0.00435957],
       ...,
       [ 0.        ,  1.        ,  0.        , ..., -0.02186158,
         0.03909984, -0.02857721],
       [ 0.        ,  0.        ,  0.        , ..., -0.01233724,
        -0.020834  ,  0.01221257],
       [ 0.        ,  0.        ,  0.        , ..., -0.02912224,
        -0.03370368,  0.00446712]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features,encoded_labels , test_size=0.2, random_state=42 ,stratify=encoded_labels)


In [ ]:
import xgboost as xgb

In [ ]:
# Convert the dataset into DMatrix format (optimized for XGBoost)
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

In [ ]:
# Define XGBoost parameters
params = {
'objective': 'multi:softmax', # Multi-class classification
'num_class': len(datagpt['Transaction Category'].unique()), # Number of classes
'eval_metric': 'merror', # Error rate metric
'max_depth': 5, # Maximum depth of a tree
'min_child_weight': 1, # Minimum sum of instance weight needed in a child
'subsample': 0.8, # Subsample ratio of the training instances
'colsample_bytree': 0.8, # Subsample ratio of columns when constructing each tree
'gamma': 0.1, # Minimum loss reduction required to make a further partition on a leaf node
'reg_alpha': 0.1, # L1 regularization term on weights
'reg_lambda': 0.1, # L2 regularization term on weights
'seed': 42 # Random seed for reproducibility
}


In [ ]:
# Train the XGBoost model
num_rounds = 100 # Number of boosting rounds
updated_model = xgb.train(params, dtrain, num_rounds,xgb_model=model)

In [ ]:
# Make predictions on the test set
y_pred = updated_model.predict(dtest)
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred, zero_division = 0)
print(f"Accuracy: {accuracy:.4f}")
print("\nConfusion Matrix:")
print(confusion_mat)
print("\nClassification Report:")
print(classification_rep)

Accuracy: 0.9346

Confusion Matrix:
[[ 1  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0 10 ...  0  0  0]
 ...
 [ 0  0  0 ...  2  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0 13]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.50      1.00      0.67         1
         1.0       0.00      0.00      0.00         1
         2.0       1.00      1.00      1.00        10
         3.0       0.90      1.00      0.95         9
         4.0       0.00      0.00      0.00         1
         5.0       0.89      1.00      0.94        16
         6.0       1.00      1.00      1.00        13
         7.0       0.90      1.00      0.95         9
         8.0       1.00      1.00      1.00         9
         9.0       0.00      0.00      0.00         1
        10.0       1.00      1.00      1.00        13
        11.0       1.00      1.00      1.00         1
        12.0       0.89      1.00      0.94         8
        13.0       1.00    

In [ ]:
from sklearn.preprocessing import OneHotEncoder
def encode_Ids(column_vector, categories):
# Create an instance of the OneHotEncoder
    encoder = OneHotEncoder(categories=[categories], sparse=False)
# Reshape the column vector to a 2D array
    column_vector = column_vector.reshape(-1, 1)
# Perform one-hot encoding on the column vector
    encoded_vector = encoder.fit_transform(column_vector)
    return encoded_vector

In [ ]:
def new_classification(matrix):
    IDs=['CPA.1','CPA_MP.1','HP.1','IPA.1','SEW0C_HI.1','SEW0C_LI.1','SEWC_CL.1','SEWC_P.1','SEWC_PA.1','SEWC_P_PL.1','TA.1','US.1']
# Perform one-hot encoding on the first column
    encoded_column1 = encode_Ids(matrix[:,0],IDs)
    column2 = (matrix[:, 1].astype(float) - 4)/(6400 - 4)

    column3 = modeld.encode(matrix[:, 2])
# Combine the columns to form the updated matrix
    updated_matrix = np.concatenate((encoded_column1, column2.reshape(-1,1), column3), axis = 1)
# Convert the new data into DMatrix format
    dnew = xgb.DMatrix(updated_matrix)
# Make predictions on the new data
    predictions = updated_model.predict(dnew)
# Inverse transform the encoded predictions to get the original category names
    predicted_categories = label_encoder.inverse_transform(predictions.astype(int))
# Print the predicted categories
    for category in predicted_categories:
        print(f"Predicted Category: {category}")
    return(predictions)

In [ ]:
newclass=np.array([['SEW0C_LI.1','60','Trendy threads - Smoking'],
                   ['SEWC_PA.1','25','IKEA - defective product refund'],
                   ['SEWC_P.1','90','Puma - Football jersey'],
                   ['SEWC_P_PL.1','340','Khan Academy - Math learning path'],
                   ['HP.1','320','Premium package health insurance - UnitedHealthcare'],
                   ['TA.1','55','Poker cards bet'],
                   ['HP.1','180','Sex on the beach bottle'],
                   ['CPA_MP.1','60','Penalty of insufficient funds']])
new_classification(newclass)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


Predicted Category: Income - Tax refund
Predicted Category: Income - Tax refund
Predicted Category: General Merchandise - Sporting goods
Predicted Category: General Services - Education
Predicted Category: General Services - Health insurance
Predicted Category: Food & Drink - Coffee and tea
Predicted Category: Food & Drink - Fast food
Predicted Category: Bank Transfers - Overdraft fees


array([44., 44., 26., 29., 31., 13., 14.,  5.], dtype=float32)

In [ ]:
with open('retrained_transaction_pickle','wb') as f:
 pickle.dump(updated_model,f)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
IDs=['CPA.1','CPA_MP.1','HP.1','IPA.1','SEW0C_HI.1','SEW0C_LI.1','SEWC_CL.1','SEWC_P.1','SEWC_PA.1','SEWC_P_PL.1','TA.1','US.1']
encoder=OneHotEncoder(categories=[IDs], sparse=False)


In [ ]:
encoder.fit_transform([['CPA.1']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
import pickle
with open('encoder_pickle','wb') as f:
 pickle.dump(encoder,f)