In [ ]:
import pickle

In [ ]:
# Load the saved model using pickle
with open("/content/transaction_pickle", 'rb') as file:
    model = pickle.load(file)

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_excel("/content/data_version_excel_v2.xlsx")
data.head()

,Unnamed: 0,Date,Id_compte,amount_transaction,category_transaction,Description,Type_transaction
0,0,2022-01-01 16:01:00,SEW0C_LI.1,3.39,Food & Drink - Coffee and tea,Latte purchase,Debit
1,1,2022-01-01 19:46:00,SEW0C_LI.1,3.39,Bank Transfers - ATM withdrawals,ATM withdrawal - $,Debit
2,2,2022-01-01 06:47:00,SEW0C_LI.1,3.39,Transportation - Public Transport,Bus fare payment,Debit
3,3,2022-01-01 19:22:00,SEW0C_LI.1,1.70,Transportation - Public Transport,Train ticket purchase,Debit
4,4,2022-01-01 05:49:00,SEW0C_LI.1,3.39,Transportation - Public Transport,Subway ride cost,Debit


In [ ]:
# Set the max_rows option to display all categories
pd.set_option('display.max_rows', None)

# Calculate the frequency counts
categories = data['category_transaction'].unique()



# Print the frequency counts
print(categories)

In [ ]:
data['category_transaction'].value_counts()

In [ ]:
IDs = data['Id_compte'].unique()



# Print the frequency counts
print(IDs)

['SEW0C_LI.1' 'SEW0C_HI.1' 'SEWC_CL.1' 'US.1' 'IPA.1' 'SEWC_P.1'
 'SEWC_PA.1' 'TA.1' 'HP.1' 'CPA.1' 'CPA_MP.1' 'SEWC_P_PL.1']


In [ ]:
datagpt=pd.read_excel("/content/mockdata.xlsx")
datagpt.head()

,Account ID,Transaction Amount,Transaction Description,Transaction Category
0,SEW0C_LI.1,20.50,Starbucks - Grande Cappuccino,Food & Drink - Coffee and tea
1,SEW0C_LI.1,15.75,Freshmart - Organic Vegetables,Supermarkets - Groceries
2,SEW0C_LI.1,50.00,Trendy Threads - Summer Dress,General Merchandise - Clothing
3,SEW0C_LI.1,8.99,City Cab - Ride to Airport,Transportation - Taxis and rideshares
4,SEW0C_LI.1,12.00,"Bookworm's Paradise - ""The Alchemist""",General Merchandise - Books


In [ ]:
double=datagpt[datagpt.duplicated()]
double

,Account ID,Transaction Amount,Transaction Description,Transaction Category
175,HP.1,10.00,GlobalBank - Other Bank Fee,Bank Transfers - Other bank fees
217,SEW0C_HI.1,6.25,Morning Brew - Medium Iced Coffee,Food & Drink - Coffee and tea
218,SEW0C_HI.1,12.50,Pizza Palace - Family Pizza Combo,Food & Drink - Restaurants
219,SEW0C_HI.1,38.00,Gas Stop - Fuel,Transportation - Gas
220,SEW0C_HI.1,16.99,Home Essentials - Cleaning Supplies,General Merchandise - Houseware
...,...,...,...,...
2938,SEW0C_LI.1,215.00,Professional House Cleaning Service,General Services - Other non-entertainment
2939,SEW0C_HI.1,185.00,Garden Landscaping and Maintenance,General Services - Other non-entertainment
2940,SEWC_CL.1,145.00,Personal Fitness Training Sessions,General Services - Other non-entertainment
2941,US.1,310.00,Legal Consultation and Advisory Services,General Services - Other non-entertainment


In [ ]:
datagpt.drop_duplicates(inplace=True)
double=datagpt[datagpt.duplicated()]
double

,Account ID,Transaction Amount,Transaction Description,Transaction Category


In [ ]:
datagpt.shape

(2136, 4)

In [ ]:
datagpt['Transaction Category'].value_counts()

Bank Transfers - Overdraft fees              81
General Services - Education                 69
Travel - Rental cars                         62
Entertainment - TV and movies                62
Credit card payment                          62
                                             ..
Transportation - Public Transport             6
Bank Transfers - Other bank fees              5
Travel - Lodging                              3
General Merchandise - Online Marketplaces     3
Medical - Veterin ary services                2
Name: Transaction Category, Length: 68, dtype: int64

In [ ]:
# Perform one-hot encoding for the "account_id" feature
encoded_data = pd.get_dummies(datagpt, columns=['Account ID'], prefix='account')
# Print the encoded data
print(encoded_data.head())

In [ ]:
one_hot_ID=encoded_data.drop(['Transaction Amount','Transaction Category','Transaction Description'], axis =1)

In [ ]:
one_hot_array=one_hot_ID.values
one_hot_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
# Extract the 'transaction amount' column
transaction_amount = datagpt['Transaction Amount']

In [ ]:
# Create an instance of the MinMaxScaler
scaler = MinMaxScaler()
# Fit and transform the transaction amount data
scaled_transaction_amount = scaler.fit_transform(transaction_amount.values.reshape(-1, 1))
# Update the 'transaction amount' column with the scaled values
datagpt['transaction_amount'] = scaled_transaction_amount
# Print the scaled 'transaction amount' column
print(datagpt['transaction_amount'])

In [ ]:
scaled_transaction_amount

array([[0.00257974],
       [0.00183709],
       [0.00719199],
       ...,
       [0.00953721],
       [0.01969981],
       [0.02908068]])

In [ ]:
datagpt.describe()

,Transaction Amount,transaction_amount
count,2136.000000,2136.000000
mean,395.883680,0.061270
std,1056.315803,0.165153
min,4.000000,0.000000
25%,22.000000,0.002814
50%,70.800000,0.010444
75%,290.000000,0.044715
max,6400.000000,1.000000


In [ ]:
from sklearn.preprocessing import LabelEncoder
# Create an instance of LabelEncoder
label_encoder = LabelEncoder()
categories=datagpt['Transaction Category'].tolist()
# Fit the encoder to the categories and transform the data
encoded_labels = label_encoder.fit_transform(categories)
# Print the encoded cat
print(encoded_labels)


[13 58 20 ... 34 34 34]


In [ ]:
label_encoder.classes_

In [ ]:
pip install sentence_transformers

In [ ]:
from sentence_transformers import SentenceTransformer
#sentences = ["This is an example sentence", "Each sentence is converted"]
modeld = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')


In [ ]:
import pickle
with open('embedding_pickle','wb') as f:
 pickle.dump(modeld,f)

In [ ]:
description=datagpt['Transaction Description'].tolist()
embeddings = modeld.encode(description)


In [ ]:
embeddings


array([[ 0.01363903,  0.02460667, -0.01300609, ...,  0.00662549,
        -0.00827213, -0.03044553],
       [ 0.01149002,  0.04829252, -0.00755107, ..., -0.02224092,
        -0.0387673 , -0.02491017],
       [-0.04387978, -0.05286455, -0.00526158, ...,  0.03130069,
        -0.05004961,  0.00435957],
       ...,
       [ 0.03993556,  0.01457984, -0.0148067 , ..., -0.02186158,
         0.03909984, -0.02857721],
       [ 0.04097003, -0.07378092, -0.02182727, ..., -0.01233724,
        -0.020834  ,  0.01221257],
       [ 0.04415144,  0.04374549,  0.0096705 , ..., -0.02912224,
        -0.03370368,  0.00446712]], dtype=float32)

In [ ]:
import numpy as np
features=np.concatenate((one_hot_array,scaled_transaction_amount,embeddings),axis = 1)
features

array([[ 0.        ,  0.        ,  0.        , ...,  0.00662549,
        -0.00827213, -0.03044553],
       [ 0.        ,  0.        ,  0.        , ..., -0.02224092,
        -0.0387673 , -0.02491017],
       [ 0.        ,  0.        ,  0.        , ...,  0.03130069,
        -0.05004961,  0.00435957],
       ...,
       [ 0.        ,  1.        ,  0.        , ..., -0.02186158,
         0.03909984, -0.02857721],
       [ 0.        ,  0.        ,  0.        , ..., -0.01233724,
        -0.020834  ,  0.01221257],
       [ 0.        ,  0.        ,  0.        , ..., -0.02912224,
        -0.03370368,  0.00446712]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features,encoded_labels , test_size=0.2, random_state=42 ,stratify=encoded_labels)


In [ ]:
import xgboost as xgb

In [ ]:
# Convert the dataset into DMatrix format (optimized for XGBoost)
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

In [ ]:
# Define XGBoost parameters
params = {
'objective': 'multi:softmax', # Multi-class classification
'num_class': len(datagpt['Transaction Category'].unique()), # Number of classes
'eval_metric': 'merror', # Error rate metric
'max_depth': 5, # Maximum depth of a tree
'min_child_weight': 1, # Minimum sum of instance weight needed in a child
'subsample': 0.8, # Subsample ratio of the training instances
'colsample_bytree': 0.8, # Subsample ratio of columns when constructing each tree
'gamma': 0.1, # Minimum loss reduction required to make a further partition on a leaf node
'reg_alpha': 0.1, # L1 regularization term on weights
'reg_lambda': 0.1, # L2 regularization term on weights
'seed': 42 # Random seed for reproducibility
}


In [ ]:
# Train the XGBoost model
num_rounds = 100 # Number of boosting rounds
updated_model = xgb.train(params, dtrain, num_rounds,xgb_model=model)

In [ ]:
# Make predictions on the test set
y_pred = updated_model.predict(dtest)
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred, zero_division = 0)
print(f"Accuracy: {accuracy:.4f}")
print("\nConfusion Matrix:")
print(confusion_mat)
print("\nClassification Report:")
print(classification_rep)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
def encode_Ids(column_vector, categories):
# Create an instance of the OneHotEncoder
    encoder = OneHotEncoder(categories=[categories], sparse=False)
# Reshape the column vector to a 2D array
    column_vector = column_vector.reshape(-1, 1)
# Perform one-hot encoding on the column vector
    encoded_vector = encoder.fit_transform(column_vector)
    return encoded_vector

In [ ]:
def new_classification(matrix):
    IDs=['CPA.1','CPA_MP.1','HP.1','IPA.1','SEW0C_HI.1','SEW0C_LI.1','SEWC_CL.1','SEWC_P.1','SEWC_PA.1','SEWC_P_PL.1','TA.1','US.1']
# Perform one-hot encoding on the first column
    encoded_column1 = encode_Ids(matrix[:,0],IDs)
    column2 = (matrix[:, 1].astype(float) - 4)/(6400 - 4)

    column3 = modeld.encode(matrix[:, 2])
# Combine the columns to form the updated matrix
    updated_matrix = np.concatenate((encoded_column1, column2.reshape(-1,1), column3), axis = 1)
# Convert the new data into DMatrix format
    dnew = xgb.DMatrix(updated_matrix)
# Make predictions on the new data
    predictions = updated_model.predict(dnew)
# Inverse transform the encoded predictions to get the original category names
    predicted_categories = label_encoder.inverse_transform(predictions.astype(int))
# Print the predicted categories
    for category in predicted_categories:
        print(f"Predicted Category: {category}")
    return(predictions)

In [ ]:
newclass=np.array([['SEW0C_LI.1','60','Trendy threads - Smoking'],
                   ['SEWC_PA.1','25','IKEA - defective product refund'],
                   ['SEWC_P.1','90','Puma - Football jersey'],
                   ['SEWC_P_PL.1','340','Khan Academy - Math learning path'],
                   ['HP.1','320','Premium package health insurance - UnitedHealthcare'],
                   ['TA.1','55','Poker cards bet'],
                   ['HP.1','180','Sex on the beach bottle'],
                   ['CPA_MP.1','60','Penalty of insufficient funds']])
new_classification(newclass)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


Predicted Category: Income - Tax refund
Predicted Category: Income - Tax refund
Predicted Category: General Merchandise - Sporting goods
Predicted Category: General Services - Education
Predicted Category: General Services - Health insurance
Predicted Category: Food & Drink - Coffee and tea
Predicted Category: Food & Drink - Fast food
Predicted Category: Bank Transfers - Overdraft fees


array([44., 44., 26., 29., 31., 13., 14.,  5.], dtype=float32)

In [ ]:
with open('retrained_transaction_pickle','wb') as f:
 pickle.dump(updated_model,f)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
IDs=['CPA.1','CPA_MP.1','HP.1','IPA.1','SEW0C_HI.1','SEW0C_LI.1','SEWC_CL.1','SEWC_P.1','SEWC_PA.1','SEWC_P_PL.1','TA.1','US.1']
encoder=OneHotEncoder(categories=[IDs], sparse=False)


In [ ]:
encoder.fit_transform([['CPA.1']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
import pickle
with open('encoder_pickle','wb') as f:
 pickle.dump(encoder,f)